[package]
name = "opendal-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.88"
dotenvy = "0.15.7"
opendal = { version = "0.49.2", features = ["services-fs", "layers-tracing"] }
tokio = { version = "1.40.0" }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
log = "0.4.22"
